name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      # 3. Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # 4. Build the application
      - name: Build application
        run: ./gradlew build --no-daemon

      # 5. Run tests
      - name: Run tests
        run: ./gradlew test --no-daemon

      # 6. Publish test results (Updated to v4)
      - name: Publish test results
        # Only publish if the test step completes successfully or fails
        # This ensures results are uploaded even if tests fail
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/test-results/test

      # 7. Run JaCoCo coverage
      - name: Generate JaCoCo coverage report
        run: ./gradlew jacocoTestReport --no-daemon

      # 8. Publish JaCoCo report (Updated to v4)
      - name: Publish JaCoCo report
        # Only publish if the JaCoCo step completes successfully
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html

      # 9. Run PIT mutation tests
      - name: Run PIT mutation tests
        run: ./gradlew pitest --no-daemon

      # 10. Publish PIT mutation report
      - name: Publish PIT mutation report
        uses: actions/upload-artifact@v4
        with:
          name: pit-report
          path: build/reports/pitest